Textiles
jeremypbeasley/realescape pull request #29
Opened 2017-11-16 01:00 UTC by jennminerva

Styled text for default.html and blog.html. Blog Index looks like the h1 size is quite large, but that may be the design, so I didn't mess with it, as I wasn't asked to.

Also, I changed the margins on .BlogContainer img so that they wouldn't be offset. I put it in a separate commit in case that was intentional and you wanted to undo it.

2017-11-16 02:12 UTC, jeremypbeasley requested changes

2017-11-16 02:12 UTC, jeremypbeasley commented on _layouts/default.html
> +		<div class="postContent column col-xs-12 col-md-8 BlogContainer">
is .BlogContainer still relevant? If not, feel free to remove it. Also, as a general rule add specific classes after generic ones. You don't want the styles you write for this to be overridden by `.column` etc.

2017-11-16 02:12 UTC, jeremypbeasley commented on _resources/_styles/base.styl
> +        margin 2em 0
Consider moving this declaration out of `.BlogContainer` and under `.postContent`. Also, can you please write all new CSS in valid CSS format, not the punctuation-less stylus format. We're eventually going to need to clean it up but why not avoid adding more to clean up ahead of time.

2017-11-16 02:12 UTC, jeremypbeasley commented on _resources/_styles/type.styl
> +sup {
I don't see where you can ever make a <sup> with markdown. If that's the case, let's remove this.

2017-11-16 02:12 UTC, jeremypbeasley commented on _resources/_styles/type.styl
> +ol {
Why are we making ordered lists semi-opaque?

2017-11-16 02:12 UTC, jeremypbeasley commented on package.json
> -    "jquery": "latest",
nice catch!

2017-11-16 02:12 UTC, jeremypbeasley commented on _resources/_styles/type.styl
> +.postContent h3 {
Let's add an H4 style as well. I know in older posts, there's a few of ####

2017-11-16 02:12 UTC, jeremypbeasley commented on _assets/master.css
>    font-family: CircularStdBook, CircularStdBold, sans-serif;
Why this font stack? First bold then... fall back to bold? Please use the variables in vars.styl if you can.

2017-11-16 02:12 UTC, jeremypbeasley commented on _resources/_styles/type.styl
> +.postContent h1 {
Consistency in code is a lot more important than perfection. I'm using thing kind of  CamelCase on all classes on this project so let's make it `PostContent`

2017-11-16 02:17 UTC, jeremypbeasley commented
One of the things to consider is if on the `default` layout, we even forced the `title` into a spot or leave it to the author to determine if it's appropriate to begin with a big H1 title or something else. 

This also gets us out of having to downscale `.postContent` styles from other styles. In other words, an H1 in a post is the same size and treatment as an an H1 on, say, the home page.

2017-11-29 01:07 UTC, jennminerva commented
@jeremypbeasley, pretty sure I got everything fixed in the footer. 

Removing the `<h2>` from the title of default markdown files made it look wonky and broken, so I restored it. Let me know if you'd rather me do something else.

2017-11-30 05:53 UTC, jeremypbeasley approved these changes

2017-11-30 06:13 UTC, jeremypbeasley commented
I had to do a pretty major refactor here and due to conflicts, ported over to another PR here: https://github.com/jeremypbeasley/realescape/pull/32

2017-11-30 06:13 UTC, closed without merging